# The events block is required by nginx but we don't need to configure anything specific for our use case, so we just set a reasonable default for worker connections
events {
	worker_connections 1024;
}

# The http block contains all the configuration related to handling HTTP requests, including MIME types, server definitions, and SSL settings
http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		# Listen on port 443 for both IPv4 and IPv6, and enable SSL for secure communication
		listen 443 ssl;
		listen [::]:443 ssl;

		server_name clados-s.42.fr;

		# Protocols and certificates for SSL/TLS encryption to ensure secure communication between clients and the server
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

		# Directory where the website files are located; nginx will look here for index files and other resources
		root /var/www/html;
		index index.php index.html index.htm;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# Crucial configuration: Forwards PHP requests to the WordPress container via FastCGI
		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
			# wordpress is the service name defined in docker-compose.yml; the default port for php-fpm is 9000
			fastcgi_pass wordpress:9000;
		}
	}
}