server {
    # Escuta estritamente na porta 443 com criptografia SSL ativa
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name clados-s.42.fr;

    # Protocolos mandatórios exigidos pelo Subject
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Diretório raiz onde os arquivos do WordPress estarão montados (Volume compartilhado)
    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Configuração crucial: Repassa requisições PHP para o container do WordPress via FastCGI
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        # wordpress é o nome do serviço definido no docker-compose.yml; a porta padrão do php-fpm é 9000
        fastcgi_pass wordpress:9000;
    }
}