[www]
; The user and group under which the PHP-FPM process will execute
user = www-data
group = www-data

; The address on which to accept FastCGI requests.
; Binding to 0.0.0.0:9000 allows connections from any container within the network
listen = 0.0.0.0:9000

; Process management configuration (dynamic spawning of PHP workers)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3